const express= require("express")
const mongoose=require("mongoose")
const cors=require("cors")
const app = express()
const dotenv= require("dotenv")
const MongoDB =require("./db/db")
const route=require('./route/route')
const path=require('path')
dotenv.config({path: './config/.env'})
MongoDB()
app.use(express.urlencoded({ extended: true }))
app.use(express.json())
const PORT =process.env.PORT
app.use(cors())
app.use('/ok', route)
app.use(express.static(path.join(__dirname, 'build')))
app.get('/*', (req,res)=>{
res.sendFile(path.join(__dirname, 'build', 'index.html'))
})
app.listen(PORT, ()=>console.log(`server in running on port ${PORT}`))